/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/public/media/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Media */
        get: operations["getPublicMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Status */
        get: operations["provider_status_api_provider_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Settings */
        put: operations["update_settings_api_settings__section__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content Profile */
        get: operations["get_content_profile_api_content_profile_get"];
        /** Put Content Profile */
        put: operations["put_content_profile_api_content_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_clips__clip_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clips */
        get: operations["list_clips_api_clips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/pending-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Approval Clips */
        get: operations["pending_approval_clips_api_clips_pending_approval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clip */
        get: operations["get_clip_api_clips__clip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clip Media */
        get: operations["get_clip_media_api_clips__clip_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/render-revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Revision */
        post: operations["render_revision_api_render_revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/render-revisions/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Render Revision */
        get: operations["get_render_revision_api_render_revisions__revision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/render-revisions/{revision_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Render Revision Media */
        get: operations["get_render_revision_media_api_render_revisions__revision_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget Summary */
        get: operations["budget_summary_api_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Costs */
        get: operations["run_costs_api_runs__run_id__costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Summary */
        get: operations["analytics_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/publications/{publication_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Publication Snapshots */
        get: operations["publication_snapshots_api_analytics_publications__publication_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Start Run Now */
        post: operations["start_run_now_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/manual-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Manual Url */
        post: operations["start_manual_url_api_runs_manual_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue Failed Run */
        post: operations["continue_failed_run_api_runs__run_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Active Run */
        post: operations["stop_active_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Run */
        get: operations["get_active_run_api_runs_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Events */
        get: operations["get_run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_runs__run_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Asset */
        post: operations["import_asset_api_assets_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Asset */
        patch: operations["update_asset_api_assets__asset_id__patch"];
        trace?: never;
    };
    "/api/assets/{asset_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset File */
        get: operations["get_asset_file_api_assets__asset_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalRequest */
        ApprovalRequest: {
            /** Decision */
            decision: string;
        };
        /** AssetListResponse */
        AssetListResponse: {
            /** Items */
            items: components["schemas"]["AssetResponse"][];
        };
        /** AssetPatchRequest */
        AssetPatchRequest: {
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[] | null;
            status?: components["schemas"]["AssetStatus"] | null;
        };
        /** AssetResponse */
        AssetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Media Type */
            media_type: string;
            /** Category */
            category: string;
            /** Storage Key */
            storage_key: string;
            /** Storage Path */
            storage_path?: string | null;
            /** Sha256 */
            sha256: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Description */
            description: string;
            /** Tags */
            tags: string[];
            /** Subjects */
            subjects: string[];
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Reusable */
            reusable: boolean;
            status: components["schemas"]["AssetStatus"];
            /** Usage Count */
            usage_count: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * AssetStatus
         * @enum {string}
         */
        AssetStatus: "active" | "quarantined" | "retired";
        /** Body_import_asset_api_assets_import_post */
        Body_import_asset_api_assets_import_post: {
            /** File */
            file: string;
            /** Category */
            category: string;
            /** License */
            license: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Tags
             * @default
             */
            tags: string;
            /**
             * Subjects
             * @default
             */
            subjects: string;
            /** Author */
            author?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** License Url */
            license_url?: string | null;
            /**
             * Attribution Required
             * @default false
             */
            attribution_required: boolean;
            /** Attribution Text */
            attribution_text?: string | null;
        };
        /** BudgetSummaryResponse */
        BudgetSummaryResponse: {
            /** Currency */
            currency: string;
            /** Month To Date Spend */
            month_to_date_spend: string;
            /** Monthly Limit */
            monthly_limit: string;
            /** Monthly Remaining */
            monthly_remaining: string;
            /** Per Clip Limit */
            per_clip_limit: string;
        };
        /** CardBackgroundRequest */
        CardBackgroundRequest: {
            /** Segment Index */
            segment_index: number;
            /**
             * Photo Asset Id
             * Format: uuid
             */
            photo_asset_id: string;
        };
        /** ClipListResponse */
        ClipListResponse: {
            /** Items */
            items: components["schemas"]["ClipResponse"][];
        };
        /** ClipPreviewResponse */
        ClipPreviewResponse: {
            /** Media Url */
            media_url: string;
            /** Mime Type */
            mime_type: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Fps */
            fps: number;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ClipResponse */
        ClipResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
            /** Story Title */
            story_title?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cost Total */
            cost_total: string;
            /** Social Metadata */
            social_metadata?: {
                [key: string]: unknown;
            } | null;
            preview: components["schemas"]["ClipPreviewResponse"];
            /** Auto Publish Due At */
            auto_publish_due_at?: string | null;
            /** Publications */
            publications: components["schemas"]["PublicationResponse"][];
        };
        /** CostEntryResponse */
        CostEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Clip Id */
            clip_id?: string | null;
            /** Provider */
            provider: string;
            /** Operation */
            operation: string;
            /** Quantity */
            quantity: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Basis */
            basis: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DashboardSummaryResponse */
        DashboardSummaryResponse: {
            /** Period */
            period: string;
            /** Clips Approved */
            clips_approved: number;
            /** Publications */
            publications: number;
            /** Views */
            views: number;
            /** Estimated Revenue */
            estimated_revenue: string;
            /** Estimated Revenue Currency */
            estimated_revenue_currency?: string | null;
            /** Next Scheduled Run At */
            next_scheduled_run_at?: string | null;
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Clip Id */
            clip_id?: string | null;
            /** Attempt */
            attempt: number;
            /** Layer */
            layer: string;
            /** Passed */
            passed: boolean;
            /** Issues */
            issues: {
                [key: string]: unknown;
            }[];
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Evaluator */
            evaluator: string;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Checks */
            checks: {
                [key: string]: boolean | string | null;
            };
        };
        /** ManualURLRequest */
        ManualURLRequest: {
            /** Url */
            url: string;
        };
        /** MetricSnapshotResponse */
        MetricSnapshotResponse: {
            /** Offset Label */
            offset_label: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Platform */
            platform: string;
            /** Views */
            views?: number | null;
            /** Likes */
            likes?: number | null;
            /** Comments */
            comments?: number | null;
            /** Shares */
            shares?: number | null;
            /** Watch Time Seconds */
            watch_time_seconds?: number | null;
            /** Average Retention Ratio */
            average_retention_ratio?: number | null;
            /** Followers Delta */
            followers_delta?: number | null;
            /** Estimated Revenue */
            estimated_revenue?: string | null;
            /** Revenue Currency */
            revenue_currency?: string | null;
            /** Revenue Basis */
            revenue_basis?: string | null;
        };
        /** OverlayRequest */
        OverlayRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "headline" | "person" | "place" | "source" | "quote" | "number";
            /** Text */
            text: string;
            /**
             * Secondary
             * @default
             */
            secondary: string;
            /** Start Seconds */
            start_seconds: number;
            /** End Seconds */
            end_seconds: number;
            /**
             * Claim Ids
             * @default []
             */
            claim_ids: string[];
            /**
             * Source Ids
             * @default []
             */
            source_ids: string[];
            /** Asset Id */
            asset_id?: string | null;
            /**
             * Placement
             * @default top
             * @enum {string}
             */
            placement: "top" | "context";
        };
        /**
         * Platform
         * @enum {string}
         */
        Platform: "youtube" | "instagram" | "tiktok" | "facebook";
        /** PublicationResponse */
        PublicationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Platform Post Id */
            platform_post_id?: string | null;
            /** Platform Url */
            platform_url?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Published At */
            published_at?: string | null;
            latest_metrics?: components["schemas"]["MetricSnapshotResponse"] | null;
        };
        /** RenderRevisionResponse */
        RenderRevisionResponse: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /**
             * Base Clip Id
             * Format: uuid
             */
            base_clip_id: string;
            /**
             * Status
             * @constant
             */
            status: "pending_review";
            /** Storage Key */
            storage_key: string;
            /** Sha256 */
            sha256: string;
            /** Composition Spec Hash */
            composition_spec_hash: string;
            request: components["schemas"]["SavedNewsRenderRequest"];
            /** Probe */
            probe: {
                [key: string]: unknown;
            };
            /** Credits */
            credits: string[];
            /** Sources */
            sources: string[];
            /** Template Version */
            template_version: string;
            /** Openrouter Calls */
            openrouter_calls: number;
            /** Tts Calls */
            tts_calls: number;
            /** Research Calls */
            research_calls: number;
            /** Transcription Calls */
            transcription_calls: number;
        };
        /** RunCostsResponse */
        RunCostsResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Currency */
            currency?: string | null;
            /** Total */
            total: string;
            /** Entries */
            entries: components["schemas"]["CostEntryResponse"][];
        };
        /** RunCreatedResponse */
        RunCreatedResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Trigger */
            trigger: string;
            /** Status */
            status: string;
            /** Outcome */
            outcome?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Attempt */
            attempt: number;
            /** Revision Retries Used */
            revision_retries_used: number;
            /** Failure Stage */
            failure_stage?: string | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /** Cost Total */
            cost_total: string;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Profile Snapshot */
            profile_snapshot: {
                [key: string]: unknown;
            };
            /** Settings Snapshot */
            settings_snapshot: {
                [key: string]: unknown;
            };
            /** Events */
            events: components["schemas"]["RunEventResponse"][];
            /** Evaluations */
            evaluations: components["schemas"]["EvaluationResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** RunEventListResponse */
        RunEventListResponse: {
            /** Items */
            items: components["schemas"]["RunEventResponse"][];
        };
        /** RunEventResponse */
        RunEventResponse: {
            /** Sequence */
            sequence: number;
            /** Type */
            type: string;
            /** Stage */
            stage?: string | null;
            /** Attempt */
            attempt: number;
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummaryResponse"][];
        };
        /** RunSummaryResponse */
        RunSummaryResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Trigger */
            trigger: string;
            /** Status */
            status: string;
            /** Outcome */
            outcome?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Attempt */
            attempt: number;
            /** Revision Retries Used */
            revision_retries_used: number;
            /** Failure Stage */
            failure_stage?: string | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /** Cost Total */
            cost_total: string;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SavedNewsRenderRequest */
        SavedNewsRenderRequest: {
            /**
             * Base Clip Id
             * Format: uuid
             */
            base_clip_id: string;
            /**
             * Template Version
             * @default modern-news-v1
             */
            template_version: string;
            /**
             * Overlays
             * @default []
             */
            overlays: components["schemas"]["OverlayRequest"][];
            /**
             * Sound Effects
             * @default []
             */
            sound_effects: components["schemas"]["SoundRequest"][];
            /** Music Asset Id */
            music_asset_id?: string | null;
            /** Brand Mark Asset Id */
            brand_mark_asset_id?: string | null;
            /**
             * Card Backgrounds
             * @default []
             */
            card_backgrounds: components["schemas"]["CardBackgroundRequest"][];
            /**
             * Transition Policy
             * @default cuts
             * @enum {string}
             */
            transition_policy: "planned" | "cuts";
            /**
             * Target Platforms
             * @default [
             *       "youtube",
             *       "instagram",
             *       "tiktok",
             *       "facebook"
             *     ]
             */
            target_platforms: components["schemas"]["Platform"][];
            /**
             * Subtitle Bottom Margin Pct
             * @default 22
             */
            subtitle_bottom_margin_pct: number;
        };
        /** SoundRequest */
        SoundRequest: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Start Seconds */
            start_seconds: number;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Gain Db
             * @default -24
             */
            gain_db: number;
            /**
             * Fade Seconds
             * @default 0.15
             */
            fade_seconds: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPublicMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    provider_status_api_provider_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    update_settings_api_settings__section__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_profile_api_content_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_content_profile_api_content_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_api_clips__clip_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clips_api_clips_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_approval_clips_api_clips_pending_approval_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clip_api_clips__clip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clip_media_api_clips__clip_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_revision_api_render_revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedNewsRenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_revision_api_render_revisions__revision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderRevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_revision_media_api_render_revisions__revision_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_api_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponse"];
                };
            };
        };
    };
    budget_summary_api_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetSummaryResponse"];
                };
            };
        };
    };
    run_costs_api_runs__run_id__costs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCostsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_summary_api_analytics_summary_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publication_snapshots_api_analytics_publications__publication_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
                trigger?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_now_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
        };
    };
    start_manual_url_api_runs_manual_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualURLRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_failed_run_api_runs__run_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_active_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_run_api_runs_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"] | null;
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after_sequence?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_runs__run_id__events_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_assets_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AssetStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_asset_api_assets_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_asset_api_assets_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asset_api_assets__asset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_file_api_assets__asset_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
